version: "3"

networks:
  app_network:
    external: true

services:
  shell:
    container_name: shell
    build:
      context: .
      dockerfile: ./apps/shell/Dockerfile
    restart: always
    ports:
      - 3000:3000
  configs:
    container_name: configs
    build:
      context: .
      dockerfile: ./apps/configs/Dockerfile
    restart: always
    ports:
      - 3001:3001
